### ISSUE TITLE
exception with debug command

### ISSUE THREAD

**Issue by LemADEC** [SimonFlash/CmdCalendar#3]
As of CmdCalendar-mc1.10.2-1.0.0.jar,
When typing /cmdcal debug, an exception is reported on console:
```
[07:41:58] [Server thread/INFO] [nucleus]: LemADEC ran the command: /CmdCal debug
[07:41:58] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'CmdCal debug' for source EntityPlayerMP['LemADEC'/274, l='Eden', x=-1214.00, y=72.00, z=5.00]: No value present
java.util.NoSuchElementException: No value present
>       at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_121]
>       at com.mcsimonflash.sponge.cmdcalendar.commands.EditTask.execute(EditTask.java:20) ~[EditTask.class:?]
>       at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:177) ~[ChildCommandElementExecutor.class:1.10.2-2254-5.2.0-BETA-2262]
>       at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:182) ~[ChildCommandElementExecutor.class:1.10.2-2254-5.2.0-BETA-2262]
>       at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:359) ~[CommandSpec.class:1.10.2-2254-5.2.0-BETA-2262]
>       at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:336) ~[SimpleDispatcher.class:1.10.2-2254-5.2.0-BETA-2262]
>       at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:291) ~[SpongeCommandManager.class:1.10.2-2254-5.2.0-BETA-2262]
>       at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) ~[bd.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) ~[me.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) ~[me.class:?]
>       at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[im.class:?]
>       at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[im.class:?]
>       at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:157) ~[PacketUtil.class:1.10.2-2254-5.2.0-BETA-2262]
>       at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:160) [CauseTracker.class:1.10.2-2254-5.2.0-BETA-2262]
>       at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156) [PacketUtil.class:1.10.2-2254-5.2.0-BETA-2262]
>       at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjh000(SourceFile:539) [fl$1.class:?]
>       at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
>       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
>       at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
>       at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
>       at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:239) [SpongeImplHooks.class:1.10.2-2254-5.2.0-BETA-2262]
>       at net.minecraft.server.MinecraftServer.redirect$onRun$zho000(MinecraftServer.java:3928) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by SimonFlash** [comment]
Caused by an improper class declaration in the command spec; fixed for the next version. (new v1.1.0)
